[package]
name = "macros"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version = "1.0", features = ['full', 'extra-traits']}
proc-macro2 = "1.0"
abcf = { path="../abcf" }
tm-abci = { git = "ssh://git@github.com/FindoraNetwork/tendermint-sys.git" }
tm-protos = { git = "ssh://git@github.com/FindoraNetwork/tendermint-sys.git" }
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
serde = { version = "1.0.124", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"